# Generated by Django 5.2.4 on 2026-07-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privacypolicyacceptance",
            name="accepted_ip",
        ),
    ]
