# Generated by Django 5.2.4 on 2026-07-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_chauffeur_created_at_chauffeur_updated_at"),
        ("compliance", "0002_remove_privacypolicyacceptance_accepted_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsOfUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=30, unique=True)),
                (
                    "title",
                    models.CharField(
                        default="Gebruiksvoorwaarden TaxiBuffer", max_length=200
                    ),
                ),
                ("body_nl", models.TextField()),
                ("effective_from", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="TermsOfUseAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "chauffeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_acceptances",
                        to="accounts.chauffeur",
                    ),
                ),
                (
                    "terms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="compliance.termsofuse",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chauffeur", "terms"),
                        name="unique_chauffeur_terms_acceptance",
                    )
                ],
            },
        ),
    ]
