# Generated by Django on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geofence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickupzone",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pickupzone",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
