# Generated by Django 5.2.4 on 2025-08-20 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geofence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("sensor_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "pickup_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="geofence.pickupzone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("date", models.DateTimeField()),
                ("status", models.BooleanField()),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sensors.sensor"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="sensor",
            index=models.Index(
                fields=["sensor_id"], name="sensors_sen_sensor__22f3a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensor",
            index=models.Index(
                fields=["pickup_zone", "active"], name="sensors_sen_pickup__40b9f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["sensor", "date"], name="sensors_sen_sensor__7a89fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(fields=["status"], name="status_idx"),
        ),
    ]
