# Generated by Django 5.2.4 on 2025-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chauffeur",
            name="vehicle_type",
            field=models.CharField(
                choices=[("auto", "Auto"), ("busje", "Busje")],
                default="auto",
                help_text="Driver's vehicle type",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chauffeur",
            name="license_plate",
            field=models.CharField(max_length=10),
        ),
    ]
