# Generated by Django 5.2.4 on 2025-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_chauffeur_vehicle_type_alter_chauffeur_license_plate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chauffeur",
            name="taxi_license_number",
            field=models.CharField(max_length=100),
        ),
    ]
