# Generated by Django 5.2.4 on 2026-03-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_chauffeur_taxi_license_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChauffeurVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=20)),
                ("nickname", models.CharField(max_length=60)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chauffeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="accounts.chauffeur",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["chauffeur", "is_current"],
                        name="accounts_ch_chauffe_111e60_idx",
                    ),
                    models.Index(
                        fields=["license_plate"], name="accounts_ch_license_0a726c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chauffeur", "license_plate"),
                        name="unique_chauffeur_license_plate",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("chauffeur",),
                        name="unique_current_vehicle_per_chauffeur",
                    ),
                ],
            },
        ),
    ]
