# Generated by Django 5.2.4 on 2026-03-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_chauffeurvehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chauffeur",
            name="license_plate",
        ),
        migrations.RemoveField(
            model_name="chauffeur",
            name="vehicle_type",
        ),
        migrations.AddField(
            model_name="chauffeurvehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[("auto", "Auto"), ("busje", "Busje")],
                default="auto",
                help_text="Vehicle type for queue routing",
                max_length=10,
            ),
        ),
    ]
