# Generated by Django 5.2.4 on 2026-03-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_chauffeur_license_plate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chauffeurvehicle",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="chauffeurvehicle",
            index=models.Index(
                fields=["is_active"], name="accounts_ch_is_acti_389721_idx"
            ),
        ),
    ]
