# Generated by Django 5.2.4 on 2026-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_chauffeurvehicle_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chauffeurvehicle",
            name="unique_chauffeur_license_plate",
        ),
        migrations.RemoveConstraint(
            model_name="chauffeurvehicle",
            name="unique_current_vehicle_per_chauffeur",
        ),
        migrations.AddConstraint(
            model_name="chauffeurvehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("chauffeur", "license_plate"),
                name="unique_chauffeur_license_plate",
            ),
        ),
        migrations.AddConstraint(
            model_name="chauffeurvehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_current", True)),
                fields=("chauffeur",),
                name="unique_current_vehicle_per_chauffeur",
            ),
        ),
    ]
