# Generated by Django 5.2.4 on 2026-03-25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_chauffeurvehicle_unique_chauffeur_license_plate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chauffeur",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chauffeur",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
