# Generated by Django 5.2.4 on 2026-07-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_chauffeur_created_at_chauffeur_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chauffeur",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Telefoonnummer van de chauffeur.", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="chauffeur",
            name="tto_name",
            field=models.CharField(
                blank=True,
                help_text="Naam van de Toegelaten Taxiorganisatie.",
                max_length=120,
            ),
        ),
    ]
