# Generated by Django 5.2.4 on 2026-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_chauffeur_phone_number_chauffeur_tto_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chauffeur",
            name="tto_name",
        ),
        migrations.AddField(
            model_name="chauffeur",
            name="tto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("florijn", "Florijn"),
                    ("mtc", "MTC"),
                    ("otc", "OTC"),
                    ("rct", "RCT"),
                    ("rtc_taxi", "RTC Taxi"),
                    ("rto", "RTO"),
                    ("rtr", "RTR"),
                    ("rts", "RTS"),
                    ("stc_taxi", "STC Taxi"),
                    ("taxi_sint_job", "Taxi Sint Job"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="chauffeur",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
