# Generated by Django 5.2.4 on 2026-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_chauffeur_tto_name_chauffeur_tto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='is_review_account',
            field=models.BooleanField(default=False),
        ),
    ]
