# Generated by Django 5.2.4 on 2025-08-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="queueentry",
            unique_together=set(),
        ),
    ]
