# Generated by Django 5.2.4 on 2025-08-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("queueing", "0002_alter_queueentry_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="queueentry",
            unique_together={("queue", "chauffeur", "created_at")},
        ),
    ]
