# Generated by Django 5.2.4 on 2025-08-28 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("queueing", "0003_alter_queueentry_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="queueentry",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_info", models.JSONField()),
                ("entry_uuid", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chauffeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.chauffeur",
                    ),
                ),
            ],
        ),
    ]
