# Generated by Django 5.2.4 on 2025-09-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0004_alter_queueentry_unique_together_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuenotification",
            name="is_cascade_notification",
            field=models.BooleanField(
                default=False,
                help_text="Whether this notification was triggered by a decline from another chauffeur",
            ),
        ),
    ]
