# Generated by Django 5.2.4 on 2025-09-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0005_queuenotification_is_cascade_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queuenotification",
            name="is_cascade_notification",
        ),
    ]
