# Generated by Django 5.2.4 on 2025-09-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0006_remove_queuenotification_is_cascade_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting in Queue"),
                    ("notified", "Notified to Leave"),
                    ("dequeued", "Dequeued (Allowed to Pickup)"),
                    ("left_zone", "Left Buffer Zone"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="queuenotification",
            name="response",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Response"),
                    ("accepted", "Accepted (Will Leave)"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
