# Generated by Django 5.2.4 on 2025-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0007_alter_queueentry_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("auto", "Auto"), ("busje", "Busje")],
                max_length=10,
                null=True,
            ),
        ),
    ]
