# Generated by Django 5.2.4 on 2025-10-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0008_queueentry_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxiqueue",
            name="notifications_paused",
            field=models.BooleanField(
                default=False,
                help_text="If true, no new notifications will be sent for this queue.",
            ),
        ),
    ]
