# Generated by Django 5.2.4 on 2025-10-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0009_taxiqueue_notifications_paused"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuenotification",
            name="sequence_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxiqueue",
            name="next_notification_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
