# Generated by Django 5.2.4 on 2026-03-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0010_queuenotification_sequence_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="license_plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
