# Generated by Django 5.2.4 on 2026-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0011_queueentry_license_plate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting in Queue"),
                    ("notified", "Notified to Leave"),
                    ("dequeued", "Dequeued (Allowed to Pickup)"),
                    ("queue_closed", "Queue Closed"),
                    ("left_zone", "Left Buffer Zone"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
