# Generated by Django 5.2.4 on 2026-07-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0012_alter_queueentry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="last_location_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="last_location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="last_location_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="location_lost_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="location_warning_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
