# Generated by Django 5.2.4 on 2026-07-14 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_chauffeur_created_at_chauffeur_updated_at"),
        ("queueing", "0013_queueentry_last_location_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChauffeurActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("queue_joined", "Aangemeld"),
                            ("queue_left", "Wachtrij verlaten"),
                            ("queue_position_changed", "Positie gewijzigd"),
                            ("location_inside", "Binnen bufferzone"),
                            ("location_outside_warning", "Buiten bufferzone"),
                            ("location_recovered", "Terug in bufferzone"),
                            ("location_unavailable", "Locatie niet beschikbaar"),
                            (
                                "location_timeout_dequeued",
                                "Verwijderd door locatiecontrole",
                            ),
                            ("notified", "Opgroepen"),
                            ("notification_accepted", "Oproep bevestigd"),
                            ("officer_dequeued", "Afgehandeld"),
                            ("system_dequeued", "Systeemverwijdering"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("message", models.TextField(blank=True)),
                ("queue_position", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "previous_queue_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("sequence_number", models.PositiveIntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chauffeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="accounts.chauffeur",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="queueing.taxiqueue",
                    ),
                ),
                (
                    "queue_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="queueing.queueentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chauffeur", "-created_at"],
                        name="queueing_ch_chauffe_e0801a_idx",
                    ),
                    models.Index(
                        fields=["queue_entry", "-created_at"],
                        name="queueing_ch_queue_e_a7ec56_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="queueing_ch_event_t_30be08_idx",
                    ),
                ],
            },
        ),
    ]
