# Generated by Django 5.2.4 on 2026-07-21 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_chauffeur_created_at_chauffeur_updated_at"),
        ("queueing", "0015_alter_queueentry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.chauffeurvehicle",
            ),
        ),
    ]
