# Generated by Django 5.2.4 on 2026-07-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0016_queueentry_vehicle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queueentry",
            old_name="license_plate",
            new_name="license_plate_snapshot",
        ),
    ]
