# Generated by Django 5.2.4 on 2026-07-21 11:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_chauffeur_created_at_chauffeur_updated_at"),
        ("queueing", "0017_rename_license_plate_queueentry_license_plate_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting in Queue"),
                    ("notified", "Notified to Leave"),
                    ("dequeued", "Dequeued (Allowed to Pickup)"),
                    ("queue_closed", "Queue Closed"),
                    ("left_zone", "Left Buffer Zone"),
                    ("left_queue", "Left Queue"),
                    ("blocked", "Blocked"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LicensePlateRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "normalized_license_plate",
                    models.CharField(db_index=True, max_length=20),
                ),
                ("display_license_plate", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lifted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_license_plate_restrictions",
                        to="accounts.officer",
                    ),
                ),
                (
                    "lifted_by_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifted_license_plate_restrictions",
                        to="accounts.officer",
                    ),
                ),
                (
                    "source_queue_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license_plate_restrictions",
                        to="queueing.queueentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["normalized_license_plate", "active"],
                        name="queueing_li_normali_bde87e_idx",
                    ),
                    models.Index(
                        fields=["active", "-created_at"],
                        name="queueing_li_active_11e70e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("normalized_license_plate",),
                        name="unique_active_license_plate_restriction",
                    )
                ],
            },
        ),
    ]
