# Generated by Django 5.2.4 on 2026-07-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0018_alter_queueentry_status_licenseplaterestriction"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="normalized_license_plate_snapshot",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
