# Generated by Django 5.2.4 on 2026-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0019_queueentry_normalized_license_plate_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chauffeuractivitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("queue_joined", "Aangemeld"),
                    ("queue_left", "Wachtrij verlaten"),
                    ("queue_position_changed", "Positie gewijzigd"),
                    ("location_inside", "Binnen bufferzone"),
                    ("location_outside_warning", "Buiten bufferzone"),
                    ("location_recovered", "Terug in bufferzone"),
                    ("location_unavailable", "Locatie niet beschikbaar"),
                    ("location_timeout_dequeued", "Verwijderd door locatiecontrole"),
                    ("notified", "Opgroepen"),
                    ("notification_accepted", "Oproep bevestigd"),
                    ("officer_dequeued", "Afgehandeld"),
                    ("system_dequeued", "Systeemverwijdering"),
                    ("blocked", "Blocked"),
                ],
                max_length=50,
            ),
        ),
    ]
