# Generated by Django 5.2.4 on 2026-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0020_alter_chauffeuractivitylog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplaterestriction',
            name='chauffeur_tto_display_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='licenseplaterestriction',
            name='chauffeur_tto_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
