# Generated by Django 5.2.4 on 2026-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0021_licenseplaterestriction_chauffeur_tto_display_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiqueue',
            name='is_test_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxiqueue',
            name='review_auto_flow_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
